[package]
cairo-version = "2.12.2"
name = "bienstar_dojo"
version = "1.7.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
register_initiative = "sozo execute bienstar_dojo-admin_system register_initiative --wait"
donate = "sozo execute bienstar_dojo-donate_system donate --wait"

[dependencies]
dojo = "1.7.1"
starknet = "2.12.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.1"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x0138b2e4650f5bba9cdb9c7a4d9567c4fceebe6219bedd0e04c13808cc926eea"